# Generated by Django 3.2.21 on 2023-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231108_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
